packages:
  - packages/*
  - sandbox

onlyBuiltDependencies:
  - esbuild

overrides:
  '@babel/helpers@<7.26.10': '>=7.26.10'
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  esbuild@<=0.24.2: '>=0.25.0'
  vite@>=5.0.0 <5.4.15: '>=5.4.15'
  vite@>=5.0.0 <5.4.16: '>=5.4.16'
  vite@>=5.0.0 <5.4.17: '>=5.4.17'
  vite@>=5.0.0 <5.4.18: '>=5.4.18'
  vite@>=5.0.0 <=5.4.18: '>=5.4.19'
